### ISSUE TITLE
CircleHover component not functioning properly

### ISSUE THREAD

**Issue by jaspreetkaur1010** [Mrityunjay20/IndieStoriesFrontend#1]
On hovering over the div, the spin functionality is also applied on '+' button.
`src/Components/GlobalComponents/CircleHover.jsx`  
 line 19, line 28

**Comment by Mrityunjay20** [comment]
1. try using 'hover:' in tailwind instead of using states, its an overkill
2. Separate the button from the div, I have commented the old code and fixed the issue
